### ISSUE TITLE
Quality of Swedish WaveNet voice degrades with long texts

### ISSUE THREAD

**Issue by miickel** [googleapis/nodejs-text-to-speech#168]
Using the API with the Swedish voice `sv-SE-Wavenet-A`, it seems that the quality of the audio degrades with longer texts.

I also posted this issue on StackOverflow, with more info and audio examples: https://stackoverflow.com/questions/54074052/googles-text-to-speech-wavenet-quality-degrades-with-long-texts

Is this expected behaviour or a bug with the Swedish voice? Because I haven't noticed this degradation of quality using any of the english voices.

Thanks!

**Comment by stephenplusplus** [comment]
Hey @miickel! Unfortunately, this issue is out of our domain, as we are just the wrapper around what the API gives us. Posting on StackOverflow was a good move-- I hope someone can chime in from the Speech team. If not, you can try one of the other methods listed here to reach them directly: https://cloud.google.com/text-to-speech/docs/support
