### ISSUE TITLE
Improve importing helper types

### ISSUE THREAD

**Issue by benhjames** [googleapis/nodejs-text-to-speech#311]
Consider this snippet:

```ts
import { TextToSpeechClient } from '@google-cloud/text-to-speech';

const textToSpeechClient = new TextToSpeechClient(/* config */);

textToSpeechClient.synthesizeSpeech({
  input: { text: 'Hello world' },
  audioConfig: { audioEncoding: 'MP3' },
});
```

This results in:

```
Type '{ audioEncoding: string; }' is not assignable to type 'IAudioConfig'.
  Types of property 'audioEncoding' are incompatible.
    Type 'string' is not assignable to type 'AudioEncoding | null | undefined'.
```

This makes sense, as it's enforcing the type of `audioEncoding`. However, trying to either cast the `MP3` string or use the `AudioEncoding` enum is a little awkward:

```ts
import { google } from '@google-cloud/text-to-speech/build/protos/protos';

textToSpeechClient.synthesizeSpeech({
  input: { text: 'Hello world' },
  audioConfig: {
    audioEncoding: google.cloud.texttospeech.v1.AudioEncoding.MP3,
  },
});
```

Is there a guarantee this build path will remain the same in future (i.e. is it part of the public API?) If not, how might we cast the `MP3` string to `AudioEncoding`, whilst also ensuring the import path for the type doesn't change?

Also, I noticed that the `AudioConfig` enum is an integer enum. Is this allowed? The public docs seem to suggest that `synthesizeSpeech` accepts strings (`MP3`, `OGG_OPUS`...) rather than integers (0, 1, 2...), but perhaps the client converts them under the hood anyway.

Thanks! 👍

**Comment by bcoe** [comment]
CC: @alexander-fenster @xiaozhenliu-gg5

**Comment by alexander-fenster** [comment]
@benhjames Thank you for this report. We are in progress of converting our auto-generated libraries to TypeScript, and sane `enum` support is quite hard (given that we must keep it compatible with `protobufjs`).

To answer your questions:

1. `build/protos/protos` will be there for the time being, but since it's not a part of the API officially, it might get changed later (even though it's unlikely).

I think the right way of dealing with it is to have a separate export from `build/src/index.d.ts` that will refer to those proto types. That way you'll be able to use it and be sure that it's a part of the official API. I will work on this and will update this issue when done.

2. As for converting enums: `protobufjs` will do the right thing when a string is passed. The thing is, the docs were originally written for JavaScript library (that did not care about types much), so now, after TypeScript conversion, we'll probably need to revisit the docs and samples and make them more type-friendly.

**Comment by alexander-fenster** [comment]
Hi @benhjames,

In v2.2.0 the types were updated to include strings where enums are expected (using the `keyof typeof` TypeScript feature). This makes it possible to use both string values and enum values in your requests.

As for properly exporting protos, https://github.com/googleapis/gapic-generator-typescript/issues/294 is the tracking issue, we'll add that export soon.
